### ISSUE TITLE
`contracts:solo-up` fails to start

### ISSUE THREAD

**Issue by ifavo** [vechain/x-app-template#24]
I have cloned the repository and run:

```shell
yarn install
yarn contracts:solo-up
```

As the README suggests.

It fails with a message:

```shell
@repo/contracts:solo-up: cache miss, executing c63372e8e844cd12
@repo/contracts:solo-up: Internal Error: @repo/contracts@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
```

I can't identify the package that seems to be missing or what command is additionally required.

What do I need to do get the embedded solo-script started?

----

Here is the complete shell log:

```shell
$ yarn install
➤ YN0070: Migrating from Yarn 1; automatically enabling the compatibility node-modules linker 👍

➤ YN0000: ┌ Resolution step
➤ YN0061: │ crypto@npm:1.0.1 is deprecated: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
➤ YN0061: │ @nomiclabs/hardhat-etherscan@npm:3.1.8 is deprecated: The @nomiclabs/hardhat-etherscan package is deprecated, please use @nomicfoundation/hardhat-verify instead
➤ YN0061: │ ganache-cli@npm:6.12.2 is deprecated: ganache-cli is now ganache; visit https://trfl.io/g7 for details
➤ YN0061: │ @humanwhocodes/config-array@npm:0.11.14 is deprecated: Use @eslint/config-array instead
➤ YN0061: │ glob@npm:7.1.7 is deprecated: Glob versions prior to v9 are no longer supported
➤ YN0061: │ glob@npm:7.2.0 is deprecated: Glob versions prior to v9 are no longer supported
➤ YN0061: │ glob@npm:7.2.3 is deprecated: Glob versions prior to v9 are no longer supported
➤ YN0061: │ glob@npm:7.1.6 is deprecated: Glob versions prior to v9 are no longer supported
➤ YN0061: │ glob@npm:5.0.15 is deprecated: Glob versions prior to v9 are no longer supported
➤ YN0032: │ keccak@npm:3.0.4: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ uuid@npm:2.0.1 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0061: │ npmlog@npm:6.0.2 is deprecated: This package is no longer supported.
➤ YN0061: │ @types/bignumber.js@npm:5.0.0 is deprecated: This is a stub types definition for bignumber.js (https://github.com/MikeMcl/bignumber.js/). bignumber.js provides its own type definitions, so you don't need @types/bignumber.js installed!
➤ YN0061: │ rimraf@npm:3.0.2 is deprecated: Rimraf versions prior to v4 are no longer supported
➤ YN0061: │ superagent@npm:8.1.2 is deprecated: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net
➤ YN0061: │ glob@npm:8.1.0 is deprecated: Glob versions prior to v9 are no longer supported
➤ YN0061: │ inflight@npm:1.0.6 is deprecated: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
➤ YN0061: │ @humanwhocodes/object-schema@npm:2.0.3 is deprecated: Use @eslint/object-schema instead
➤ YN0032: │ fsevents@npm:2.3.3: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ node-addon-api@npm:2.0.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ are-we-there-yet@npm:3.0.1 is deprecated: This package is no longer supported.
➤ YN0061: │ gauge@npm:4.0.4 is deprecated: This package is no longer supported.
➤ YN0032: │ secp256k1@npm:4.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ ethereum-bloom-filters@npm:1.1.0 is deprecated: do not use this package use package versions above as this can miss some topics
➤ YN0061: │ ipfs-core-types@npm:0.8.4 is deprecated: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details
➤ YN0061: │ ipfs-core-utils@npm:0.12.2 is deprecated: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details
➤ YN0061: │ core-js@npm:2.6.12 is deprecated: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ @truffle/error@npm:0.1.1 is deprecated: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
➤ YN0061: │ @truffle/contract-schema@npm:3.4.16 is deprecated: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @truffle/interface-adapter@npm:0.5.37 is deprecated: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
➤ YN0061: │ multiaddr-to-uri@npm:8.0.0 is deprecated: This module is deprecated, please upgrade to @multiformats/multiaddr-to-uri
➤ YN0061: │ @truffle/blockchain-utils@npm:0.1.9 is deprecated: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
➤ YN0061: │ multiaddr@npm:10.0.1 is deprecated: This module is deprecated, please upgrade to @multiformats/multiaddr
➤ YN0061: │ @truffle/debug-utils@npm:6.0.57 is deprecated: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0061: │ z-schema@npm:5.0.6 is deprecated: has issues with node 14
➤ YN0061: │ @web3modal/html@npm:2.7.1 is deprecated: Please use new @web3modal/wagmi package
➤ YN0061: │ @web3modal/ethereum@npm:2.7.1 is deprecated: Please use new @web3modal/wagmi package
➤ YN0061: │ @ensdomains/ens@npm:0.4.5 is deprecated: Please use @ensdomains/ens-contracts
➤ YN0061: │ rimraf@npm:2.7.1 is deprecated: Rimraf versions prior to v4 are no longer supported
➤ YN0061: │ @ensdomains/resolver@npm:0.2.4 is deprecated: Please use @ensdomains/ens-contracts
➤ YN0061: │ @walletconnect/sign-client@npm:2.10.2 is deprecated: Reliability and performance greatly improved - please see https://github.com/WalletConnect/walletconnect-monorepo/releases
➤ YN0061: │ testrpc@npm:0.0.1 is deprecated: testrpc has been renamed to ganache-cli, please use this package from now on.
➤ YN0061: │ cids@npm:0.7.5 is deprecated: This module has been superseded by the multiformats module
➤ YN0061: │ multicodec@npm:0.5.7 is deprecated: This module has been superseded by the multiformats module
➤ YN0061: │ multicodec@npm:1.0.4 is deprecated: This module has been superseded by the multiformats module
➤ YN0061: │ multibase@npm:0.6.1 is deprecated: This module has been superseded by the multiformats module
➤ YN0061: │ multibase@npm:0.7.0 is deprecated: This module has been superseded by the multiformats module
➤ YN0061: │ @motionone/vue@npm:10.16.4 is deprecated: Motion One for Vue is deprecated. Use Oku Motion instead https://oku-ui.com/motion
➤ YN0061: │ @truffle/codec@npm:0.17.3 is deprecated: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
➤ YN0061: │ @walletconnect/sign-client@npm:2.11.0 is deprecated: Reliability and performance greatly improved - please see https://github.com/WalletConnect/walletconnect-monorepo/releases
➤ YN0032: │ bufferutil@npm:4.0.8: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ utf-8-validate@npm:5.0.10: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ mkdirp-promise@npm:5.0.1 is deprecated: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
➤ YN0061: │ @truffle/abi-utils@npm:1.0.3 is deprecated: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
➤ YN0061: │ @truffle/compile-common@npm:0.9.8 is deprecated: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
➤ YN0061: │ @truffle/error@npm:0.2.2 is deprecated: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
➤ YN0032: │ @parcel/watcher@npm:2.4.1: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ node-addon-api@npm:7.1.0: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0002: │ @nomiclabs/hardhat-truffle5@npm:2.0.7 [9fdbd] doesn't provide web3-core-helpers (pc0064), requested by @nomiclabs/truffle-contract
➤ YN0002: │ @nomiclabs/hardhat-truffle5@npm:2.0.7 [9fdbd] doesn't provide web3-core-promievent (p2a600), requested by @nomiclabs/truffle-contract
➤ YN0002: │ @nomiclabs/hardhat-truffle5@npm:2.0.7 [9fdbd] doesn't provide web3-eth-abi (p388ef), requested by @nomiclabs/truffle-contract
➤ YN0002: │ @nomiclabs/hardhat-truffle5@npm:2.0.7 [9fdbd] doesn't provide web3-utils (p28eb3), requested by @nomiclabs/truffle-contract
➤ YN0002: │ @repo/contracts@workspace:apps/contracts doesn't provide @types/node (pa3239), requested by @nomicfoundation/hardhat-toolbox
➤ YN0002: │ @repo/contracts@workspace:apps/contracts doesn't provide @types/node (p15518), requested by ts-node
➤ YN0002: │ @repo/contracts@workspace:apps/contracts doesn't provide react (p86287), requested by react-slot-counter
➤ YN0002: │ @repo/contracts@workspace:apps/contracts doesn't provide react-dom (pdf171), requested by react-slot-counter
➤ YN0002: │ @repo/contracts@workspace:apps/contracts doesn't provide web3 (pe15b1), requested by @nomiclabs/hardhat-truffle5
➤ YN0002: │ @repo/contracts@workspace:apps/contracts doesn't provide web3 (p0103a), requested by @nomiclabs/hardhat-web3
➤ YN0002: │ @vechain/dapp-kit-react@npm:1.0.12 doesn't provide @types/react (pc71bb), requested by @lit/react
➤ YN0002: │ dns-over-http-resolver@npm:1.2.3 doesn't provide node-fetch (p89343), requested by native-fetch
➤ YN0002: │ swagger-parser@npm:10.0.3 doesn't provide openapi-types (p54c62), requested by @apidevtools/swagger-parser
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 17s 29ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:1.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ z-schema@npm:5.0.6 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zustand@npm:4.5.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 19s 404ms
➤ YN0000: ┌ Link step
➤ YN0007: │ @swc/core@npm:1.5.7 [08a68] must be built because it never has been before or the last one failed
➤ YN0007: │ keccak@npm:3.0.4 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.20.2 must be built because it never has been before or the last one failed
➤ YN0007: │ secp256k1@npm:4.0.3 must be built because it never has been before or the last one failed
➤ YN0007: │ web3-bzz@npm:1.10.4 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0007: │ web3-bzz@npm:1.10.0 must be built because it never has been before or the last one failed
➤ YN0007: │ bufferutil@npm:4.0.8 must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.64 must be built because it never has been before or the last one failed
➤ YN0007: │ utf-8-validate@npm:5.0.10 must be built because it never has been before or the last one failed
➤ YN0007: │ protobufjs@npm:6.11.4 must be built because it never has been before or the last one failed
➤ YN0007: │ web3-shh@npm:1.10.4 must be built because it never has been before or the last one failed
➤ YN0007: │ web3-shh@npm:1.10.0 must be built because it never has been before or the last one failed
➤ YN0007: │ web3@npm:1.10.4 must be built because it never has been before or the last one failed
➤ YN0007: │ web3@npm:1.10.0 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 24s 531ms
➤ YN0000: Done with warnings in 1m 2s

$ yarn contracts:solo-up
╭──────────────────────────────────────────────────────────────────────╮
│                                                                      │
│                  Update available v1.13.3 ≫ v2.1.1                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v2.1.1    │
│           Run "npx @turbo/codemod@latest update" to update           │
│                                                                      │
│        Follow @turborepo for updates: https://x.com/turborepo        │
╰──────────────────────────────────────────────────────────────────────╯
• Packages in scope: @repo/config-contract, @repo/contracts, @repo/typescript-config, @repo/utils, x-dapp-backend, x-dapp-frontend
• Running solo-up in 6 packages
• Remote caching disabled
@repo/contracts:solo-up: cache miss, executing c63372e8e844cd12
@repo/contracts:solo-up: Internal Error: @repo/contracts@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
@repo/contracts:solo-up:     at V0.getCandidates (/Users/favo/.yarn/releases/yarn-3.6.1.cjs:435:5145)
@repo/contracts:solo-up:     at kf.getCandidates (/Users/favo/.yarn/releases/yarn-3.6.1.cjs:391:1264)
@repo/contracts:solo-up:     at /Users/favo/.yarn/releases/yarn-3.6.1.cjs:439:8033
@repo/contracts:solo-up:     at df (/Users/favo/.yarn/releases/yarn-3.6.1.cjs:390:11070)
@repo/contracts:solo-up:     at ge (/Users/favo/.yarn/releases/yarn-3.6.1.cjs:439:8013)
@repo/contracts:solo-up:     at async Promise.allSettled (index 0)
@repo/contracts:solo-up:     at async io (/Users/favo/.yarn/releases/yarn-3.6.1.cjs:390:10398)
@repo/contracts:solo-up:     at async /Users/favo/.yarn/releases/yarn-3.6.1.cjs:439:8545
@repo/contracts:solo-up:     at async ti.startProgressPromise (/Users/favo/.yarn/releases/yarn-3.6.1.cjs:390:47579)
@repo/contracts:solo-up:     at async je.resolveEverything (/Users/favo/.yarn/releases/yarn-3.6.1.cjs:439:6573)
@repo/contracts:solo-up: ERROR: command finished with error: command (/github/x-app-template/apps/contracts) /private/../xfs-a69741d7/yarn run solo-up exited (1)
@repo/contracts#solo-up: command (/github/x-app-template/apps/contracts) /private/../xfs-a69741d7/yarn run solo-up exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    665ms 
Failed:    @repo/contracts#solo-up

 ERROR  run failed: command  exited (1)
```

**Comment by ifavo** [comment]
Downgrading yarn to classic (v1) solved it, this is what worked for me:

```shell
yarn set version classic
yarn install
yarn contracts:solo-up
yarn contracts:deploy:solo
yarn dev
```
